### PR TITLE
PE-2875: removes the import of snapshot entries

### PR DESCRIPTION
**Pull request by matibat**
--- Releases ---
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3e7caao7oljeo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4qj9mmm3i5sl0

### CODE REVIEW

**Comment by matibat** [comment]
It's missing the android change-log!

**Comment by matibat** [comment]
So, I'm almost sure this one indeed doesn't need a DB migration. Is it right?

**Review by thiagocarvalhodev — APPROVED** [review]
LGTM

**Review by agsuy — APPROVED** [review]
LGTM

**Pull request merged**
