### PR TITLE
Update Dart sdk and packages versions

### PR DESCRIPTION
**Pull request by thiagocarvalhodev**
## Upgrade Flutter version

Update the Dart SDK and the versions of outdated packages.

### Motivation
With the current version of Dart `2.13.0` we aren't able to update the version of Flutter to the latest: `2.10.3`. To know more about the improvements in this version, see: [Flutter 2.10.0 improvements](https://medium.com/flutter/whats-new-in-flutter-2-10-5aafb0314b12).

### CODE REVIEW

**Comment by jdaev** [comment]
https://github.com/ardriveapp/ardrive-web/pull/351

**Comment by thiagocarvalhodev** [comment]
@jdaev , thanks, I didn't see this PR. Closing this one.

**Comment by jdaev** [comment]
@thiagocarvalhodev 
Nah. Let's leave it open as a draft. If you wanna do this please create a ticket for this task and we can proceed with this and PR. What's with the changes to the application name?

**Comment by thiagocarvalhodev** [comment]
> What's with the changes to the application name?

Please see [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#full-flutter-app-migration).

**Comment by thiagocarvalhodev** [comment]
Closing as we already have a PR doing it #626 .

**Pull request closed without merging**
